<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drive" lowerBound="1" upperBound="-1"
        eType="#//Car"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EReference" name="equip" lowerBound="1" upperBound="-1"
        eType="#//Engine" eOpposite="#//Engine/ownedcar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regno" lowerBound="1" eType="#//Number"
        eOpposite="#//Number/regCar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Number">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regCar" lowerBound="1"
        eType="#//Car" eOpposite="#//Car/regno"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Manual"
        eOpposite="#//Manual/engineRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedcar" lowerBound="1"
        eType="#//Car" eOpposite="#//Car/equip"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manual">
    <eStructuralFeatures xsi:type="ecore:EReference" name="engineRef" lowerBound="1"
        eType="#//Engine" eOpposite="#//Engine/reference"/>
  </eClassifiers>
</ecore:EPackage>
